version: "3"
services:

  auth:
    build:
      context: ./auth
    ports:
      - "3001:3001"

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth