version: '3'
services:
  enrollment:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: lms-enrollment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@ssword
